// source: simufly.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.kl.simufly.ControlCmd', null, global);
goog.exportSymbol('proto.kl.simufly.ControlCmd.cmdType', null, global);
goog.exportSymbol('proto.kl.simufly.ModifyParameter', null, global);
goog.exportSymbol('proto.kl.simufly.ModifyParameter.Parameter', null, global);
goog.exportSymbol('proto.kl.simufly.SignalManage', null, global);
goog.exportSymbol('proto.kl.simufly.SignalManage.Signal', null, global);
goog.exportSymbol('proto.kl.simufly.SimuData', null, global);
goog.exportSymbol('proto.kl.simufly.StateResponse', null, global);
goog.exportSymbol('proto.kl.simufly.StateResponse.stateType', null, global);
goog.exportSymbol('proto.kl.simufly.Type', null, global);
goog.exportSymbol('proto.kl.simufly.Type.messageType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.ControlCmd = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kl.simufly.ControlCmd, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.ControlCmd.displayName = 'proto.kl.simufly.ControlCmd';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.ModifyParameter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kl.simufly.ModifyParameter.repeatedFields_, null);
};
goog.inherits(proto.kl.simufly.ModifyParameter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.ModifyParameter.displayName = 'proto.kl.simufly.ModifyParameter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.ModifyParameter.Parameter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kl.simufly.ModifyParameter.Parameter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.ModifyParameter.Parameter.displayName = 'proto.kl.simufly.ModifyParameter.Parameter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.SignalManage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kl.simufly.SignalManage.repeatedFields_, null);
};
goog.inherits(proto.kl.simufly.SignalManage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.SignalManage.displayName = 'proto.kl.simufly.SignalManage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.SignalManage.Signal = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kl.simufly.SignalManage.Signal, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.SignalManage.Signal.displayName = 'proto.kl.simufly.SignalManage.Signal';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.SimuData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kl.simufly.SimuData.repeatedFields_, null);
};
goog.inherits(proto.kl.simufly.SimuData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.SimuData.displayName = 'proto.kl.simufly.SimuData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.StateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kl.simufly.StateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.StateResponse.displayName = 'proto.kl.simufly.StateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kl.simufly.Type = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kl.simufly.Type, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kl.simufly.Type.displayName = 'proto.kl.simufly.Type';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.ControlCmd.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.ControlCmd.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.ControlCmd} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ControlCmd.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdType: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.ControlCmd}
 */
proto.kl.simufly.ControlCmd.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.ControlCmd;
  return proto.kl.simufly.ControlCmd.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.ControlCmd} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.ControlCmd}
 */
proto.kl.simufly.ControlCmd.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.kl.simufly.ControlCmd.cmdType} */ (reader.readEnum());
      msg.setCmdType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.ControlCmd.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.ControlCmd.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.ControlCmd} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ControlCmd.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.kl.simufly.ControlCmd.cmdType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.kl.simufly.ControlCmd.cmdType = {
  START: 0,
  STOP: 1,
  TERMINATE: 2
};

/**
 * optional cmdType cmd_type = 1;
 * @return {!proto.kl.simufly.ControlCmd.cmdType}
 */
proto.kl.simufly.ControlCmd.prototype.getCmdType = function() {
  return /** @type {!proto.kl.simufly.ControlCmd.cmdType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.kl.simufly.ControlCmd.cmdType} value
 * @return {!proto.kl.simufly.ControlCmd} returns this
 */
proto.kl.simufly.ControlCmd.prototype.setCmdType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.ControlCmd} returns this
 */
proto.kl.simufly.ControlCmd.prototype.clearCmdType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.ControlCmd.prototype.hasCmdType = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kl.simufly.ModifyParameter.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.ModifyParameter.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.ModifyParameter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.ModifyParameter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ModifyParameter.toObject = function(includeInstance, msg) {
  var f, obj = {
    parameterList: jspb.Message.toObjectList(msg.getParameterList(),
    proto.kl.simufly.ModifyParameter.Parameter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.ModifyParameter}
 */
proto.kl.simufly.ModifyParameter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.ModifyParameter;
  return proto.kl.simufly.ModifyParameter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.ModifyParameter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.ModifyParameter}
 */
proto.kl.simufly.ModifyParameter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.kl.simufly.ModifyParameter.Parameter;
      reader.readMessage(value,proto.kl.simufly.ModifyParameter.Parameter.deserializeBinaryFromReader);
      msg.addParameter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.ModifyParameter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.ModifyParameter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.ModifyParameter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ModifyParameter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParameterList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.kl.simufly.ModifyParameter.Parameter.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.ModifyParameter.Parameter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.ModifyParameter.Parameter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ModifyParameter.Parameter.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    portIndex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    value: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.ModifyParameter.Parameter}
 */
proto.kl.simufly.ModifyParameter.Parameter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.ModifyParameter.Parameter;
  return proto.kl.simufly.ModifyParameter.Parameter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.ModifyParameter.Parameter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.ModifyParameter.Parameter}
 */
proto.kl.simufly.ModifyParameter.Parameter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPortIndex(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.ModifyParameter.Parameter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.ModifyParameter.Parameter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.ModifyParameter.Parameter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional uint32 block_id = 1;
 * @return {number}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.getBlockId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.setBlockId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.clearBlockId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.hasBlockId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 port_index = 2;
 * @return {number}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.getPortIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.setPortIndex = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.clearPortIndex = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.hasPortIndex = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double value = 3;
 * @return {number}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.setValue = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.ModifyParameter.Parameter} returns this
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.clearValue = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.ModifyParameter.Parameter.prototype.hasValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Parameter parameter = 1;
 * @return {!Array<!proto.kl.simufly.ModifyParameter.Parameter>}
 */
proto.kl.simufly.ModifyParameter.prototype.getParameterList = function() {
  return /** @type{!Array<!proto.kl.simufly.ModifyParameter.Parameter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kl.simufly.ModifyParameter.Parameter, 1));
};


/**
 * @param {!Array<!proto.kl.simufly.ModifyParameter.Parameter>} value
 * @return {!proto.kl.simufly.ModifyParameter} returns this
*/
proto.kl.simufly.ModifyParameter.prototype.setParameterList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.kl.simufly.ModifyParameter.Parameter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kl.simufly.ModifyParameter.Parameter}
 */
proto.kl.simufly.ModifyParameter.prototype.addParameter = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.kl.simufly.ModifyParameter.Parameter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kl.simufly.ModifyParameter} returns this
 */
proto.kl.simufly.ModifyParameter.prototype.clearParameterList = function() {
  return this.setParameterList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kl.simufly.SignalManage.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.SignalManage.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.SignalManage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.SignalManage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SignalManage.toObject = function(includeInstance, msg) {
  var f, obj = {
    signalList: jspb.Message.toObjectList(msg.getSignalList(),
    proto.kl.simufly.SignalManage.Signal.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.SignalManage}
 */
proto.kl.simufly.SignalManage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.SignalManage;
  return proto.kl.simufly.SignalManage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.SignalManage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.SignalManage}
 */
proto.kl.simufly.SignalManage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.kl.simufly.SignalManage.Signal;
      reader.readMessage(value,proto.kl.simufly.SignalManage.Signal.deserializeBinaryFromReader);
      msg.addSignal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.SignalManage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.SignalManage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.SignalManage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SignalManage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSignalList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.kl.simufly.SignalManage.Signal.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.SignalManage.Signal.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.SignalManage.Signal.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.SignalManage.Signal} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SignalManage.Signal.toObject = function(includeInstance, msg) {
  var f, obj = {
    monitor: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    record: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    blockId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    portIndex: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.SignalManage.Signal}
 */
proto.kl.simufly.SignalManage.Signal.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.SignalManage.Signal;
  return proto.kl.simufly.SignalManage.Signal.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.SignalManage.Signal} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.SignalManage.Signal}
 */
proto.kl.simufly.SignalManage.Signal.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMonitor(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecord(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPortIndex(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.SignalManage.Signal.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.SignalManage.Signal.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.SignalManage.Signal} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SignalManage.Signal.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional bool monitor = 1;
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.getMonitor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.setMonitor = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.clearMonitor = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.hasMonitor = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool record = 2;
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.getRecord = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.setRecord = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.clearRecord = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.hasRecord = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint32 block_id = 3;
 * @return {number}
 */
proto.kl.simufly.SignalManage.Signal.prototype.getBlockId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.setBlockId = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.clearBlockId = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.hasBlockId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 port_index = 4;
 * @return {number}
 */
proto.kl.simufly.SignalManage.Signal.prototype.getPortIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.setPortIndex = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SignalManage.Signal} returns this
 */
proto.kl.simufly.SignalManage.Signal.prototype.clearPortIndex = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SignalManage.Signal.prototype.hasPortIndex = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Signal signal = 1;
 * @return {!Array<!proto.kl.simufly.SignalManage.Signal>}
 */
proto.kl.simufly.SignalManage.prototype.getSignalList = function() {
  return /** @type{!Array<!proto.kl.simufly.SignalManage.Signal>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kl.simufly.SignalManage.Signal, 1));
};


/**
 * @param {!Array<!proto.kl.simufly.SignalManage.Signal>} value
 * @return {!proto.kl.simufly.SignalManage} returns this
*/
proto.kl.simufly.SignalManage.prototype.setSignalList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.kl.simufly.SignalManage.Signal=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kl.simufly.SignalManage.Signal}
 */
proto.kl.simufly.SignalManage.prototype.addSignal = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.kl.simufly.SignalManage.Signal, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kl.simufly.SignalManage} returns this
 */
proto.kl.simufly.SignalManage.prototype.clearSignalList = function() {
  return this.setSignalList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kl.simufly.SimuData.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.SimuData.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.SimuData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.SimuData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SimuData.toObject = function(includeInstance, msg) {
  var f, obj = {
    blockId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    portIndex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    valueList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.SimuData}
 */
proto.kl.simufly.SimuData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.SimuData;
  return proto.kl.simufly.SimuData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.SimuData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.SimuData}
 */
proto.kl.simufly.SimuData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBlockId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPortIndex(value);
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addValue(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.SimuData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.SimuData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.SimuData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.SimuData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getValueList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
};


/**
 * optional uint32 block_id = 1;
 * @return {number}
 */
proto.kl.simufly.SimuData.prototype.getBlockId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.setBlockId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.clearBlockId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SimuData.prototype.hasBlockId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 port_index = 2;
 * @return {number}
 */
proto.kl.simufly.SimuData.prototype.getPortIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.setPortIndex = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.clearPortIndex = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.SimuData.prototype.hasPortIndex = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated double value = 3;
 * @return {!Array<number>}
 */
proto.kl.simufly.SimuData.prototype.getValueList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.setValueList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.addValue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kl.simufly.SimuData} returns this
 */
proto.kl.simufly.SimuData.prototype.clearValueList = function() {
  return this.setValueList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.StateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.StateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.StateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.StateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    stateType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ret: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.StateResponse}
 */
proto.kl.simufly.StateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.StateResponse;
  return proto.kl.simufly.StateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.StateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.StateResponse}
 */
proto.kl.simufly.StateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.kl.simufly.StateResponse.stateType} */ (reader.readEnum());
      msg.setStateType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.StateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.StateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.StateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.StateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.kl.simufly.StateResponse.stateType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRet();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.kl.simufly.StateResponse.stateType = {
  CONNECTREP: 0,
  STARTREP: 1,
  STOPREP: 2,
  TERMINATEREP: 3
};

/**
 * optional stateType state_type = 1;
 * @return {!proto.kl.simufly.StateResponse.stateType}
 */
proto.kl.simufly.StateResponse.prototype.getStateType = function() {
  return /** @type {!proto.kl.simufly.StateResponse.stateType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.kl.simufly.StateResponse.stateType} value
 * @return {!proto.kl.simufly.StateResponse} returns this
 */
proto.kl.simufly.StateResponse.prototype.setStateType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.kl.simufly.StateResponse} returns this
 */
proto.kl.simufly.StateResponse.prototype.clearStateType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kl.simufly.StateResponse.prototype.hasStateType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool ret = 2;
 * @return {boolean}
 */
proto.kl.simufly.StateResponse.prototype.getRet = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.kl.simufly.StateResponse} returns this
 */
proto.kl.simufly.StateResponse.prototype.setRet = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kl.simufly.Type.prototype.toObject = function(opt_includeInstance) {
  return proto.kl.simufly.Type.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kl.simufly.Type} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.Type.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kl.simufly.Type}
 */
proto.kl.simufly.Type.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kl.simufly.Type;
  return proto.kl.simufly.Type.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kl.simufly.Type} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kl.simufly.Type}
 */
proto.kl.simufly.Type.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kl.simufly.Type.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kl.simufly.Type.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kl.simufly.Type} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kl.simufly.Type.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.kl.simufly.Type.messageType = {
  CONTROLCMD: 0,
  MODIFYPARAMETER: 1,
  SIGNALMANAGE: 2,
  SIMUDATA: 3,
  STATERESPONSE: 4
};

goog.object.extend(exports, proto.kl.simufly);
